### ISSUE TITLE
WAITING TO BE SUBMITTED even after being on same page for 24hrs

### ISSUE THREAD

**Issue by DM-444** [zkparty/trusted-setup-frontend#148]
<img width="774" alt="KZG" src="https://user-images.githubusercontent.com/113819245/212754906-fb279f2f-d012-4e56-9152-8cf6f843842e.png">
it's been 24 hrs. I kept my PC ON  and still getting WAITING TO BE SUBMITTED.. not able to contribute.. please help me. I stayed on the same page for more than 18 hrs

**Comment by NicoSerranoP** [comment]
Could you check the developer console (Ctrl + Shift + I) and share an screenshot with us? The lobby has been super packed this week and it might be related to it but I want to make sure you are not getting any errors

**Comment by DM-444** [comment]
<img width="412" alt="D_con_1" src="https://user-images.githubusercontent.com/113819245/212822111-599bbba5-ed97-4e26-949d-42d5a1bbf45d.png">
<img width="416" alt="D_console" src="https://user-images.githubusercontent.com/113819245/212822120-b715bfac-3d7d-4fee-9c6e-e281f1ad7359.png">

**Comment by BigMurry** [comment]
In my case, plenty of `another contribution in progress` then the session timeout.


![image](https://user-images.githubusercontent.com/12495406/212851726-03326321-ce6f-4c83-aaa4-dcf8cb3192b6.png)

**Comment by DanchuB** [comment]
![git f](https://user-images.githubusercontent.com/90562472/212903327-6ac769c4-5723-484c-b2d3-5029a12165bd.png)

**Comment by NicoSerranoP** [comment]
@DM-444 sorry about the inconveniences, from what I see from your console logs, there are normal sequencer/server responses. The lobby logic is the following:

If the lobby is not full (less than 5,000) then you can enter into that pool. In that pool, a participant is selected randomly every 1 minute (the website header indicates 3 minutes but that is the worst case scenario. Our average contribution time so far has been around 47s). This logic is different than a queue, that is why we called a lobby. We decided to take this approach so when users disconnect from the system, they can reconnect again and have the same odds to be selected as before.

In your specific case we will need to keep waiting. Don't worry because we have enough time to contribute (the ceremony ends in two months). There are a couple of alternatives you could take:

1. Use any other client implementation (you will need some developer background to make it work): [check the alternatives here](https://github.com/ethereum/kzg-ceremony#client-implementations)

2. There is an unofficial website that allows you to contribute to the ceremony: [DogeKZG](https://www.dogekzg.com/)

**Comment by BigMurry** [comment]
@NicoSerranoP 
The timeout issue has been resolved. But I've left the web tab running in the background for nearly 3 days, it's still WAITING TO BE SUBMITTED.

**Comment by NicoSerranoP** [comment]
@BigMurry yes right now the lobby is packed. If you want you could return later on, we still have 40 days to go
