### ISSUE TITLE
Click on the page button can not jump problem

### ISSUE THREAD

**Issue by cuikunshuo** [zkparty/trusted-setup-frontend#156]
Hello! I don't know why I click this button on the page, nothing happens, there is no way to jump to the next page, I can't see any problem at the moment, I can't jump even after using multiple browsers, can you help me to solve it?
<img width="583" alt="1674973408081" src="https://user-images.githubusercontent.com/23049724/215308970-49119c21-af9c-4951-829d-f08ea33adcba.png">
<img width="1036" alt="1674973487730" src="https://user-images.githubusercontent.com/23049724/215309040-169570e3-45d7-4e6c-a323-c413ecd0479b.png">

**Comment by NicoSerranoP** [comment]
Hi there! Try deleting all the storage in the [https://oidc.signinwithethereum.org/](https://oidc.signinwithethereum.org/) page. This could be caused because the SIWE is linked to another wallet provider. To delete you can go to Dev Tools/ Application / Storage:
![image](https://user-images.githubusercontent.com/38594836/215555506-fb15b6ce-5068-4803-9841-f7d4ff27c751.png)

**Comment by cuikunshuo** [comment]
Thank you, I followed your method to solve the problem.
