### ISSUE TITLE
The address has already contributed to the ceremony, and can't find the address in record

### ISSUE THREAD

**Issue by basangtopy** [zkparty/trusted-setup-frontend#200]
I tried to contribute to the ceremony, and I waited for hours in the lobby. 
After the waiting period, I got the message; "You have been called upon now".
![Shot2](https://github.com/zkparty/trusted-setup-frontend/assets/36514194/db11c8da-bb1c-4d97-ab2d-a106bb19301c)

After waiting for few moment, i got another message that; "Something went wrong".
![Shot3](https://github.com/zkparty/trusted-setup-frontend/assets/36514194/37f5b0af-0b07-4f41-9c7e-e5bc5545da9d)
I tried reloading as indicated, but the error message persisted.

Then I tried to sign in to start all over2, but i got another error saying; "The address has already contributed to the ceremony"
![Shot1](https://github.com/zkparty/trusted-setup-frontend/assets/36514194/36181ffa-018c-4b1c-81ae-20c78553295b)

I looked up the address on the "record" page, but it wasn't found there.

I don't know the next step to take, as this has happened when i tried with two of my addresses and my Github account, making three instances.
And I understand that the ceremony will end in just few hours' time. What can I do? As I don't want to miss out on this rare opportunity to contribute to the blockchain.

A response with solutions and way forward would be really appreciated. Please help.

**Comment by TR3835** [comment]
I got the same problem, when I access to contribute the open contribution date is 1 day left but when I finish contribution the date is minus. (as picture below) don't sure the problem came from this?
I can't make the contribution again, what should i do

![image](https://github.com/zkparty/trusted-setup-frontend/assets/99732459/2f67ebb0-771f-4fc0-904f-4c901d955b83)
