### ISSUE TITLE
Is sequencer stuck?

### ISSUE THREAD

**Issue by james-prysm** [zkparty/trusted-setup-frontend#96]
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/90280386/205409736-ac785342-c31d-4b47-ad44-9a487388c8dd.png">

Been waiting quite some time and over a hundred attempts later still shows the same wondering if it got stuck or was paused but the site says the sequencer is online. I might try to open a PR for attempts if there's interest in adding that to the page.

**Comment by NicoSerranoP** [comment]
Hi James @james-prysm! Sometimes the sequencer gets stuck, sends the "another contribution in progress" message for while and after that sends "unknown session id" (kicks out the participant from the lobby). That issue is being reviewed by the sequencer team  [](https://github.com/ethereum/kzg-ceremony-sequencer/).

Meanwhile, we implemented a fix to avoid leaving the user in the lobby waiting and infinite loading. The current PR is #97

**Comment by PlasmaPower** [comment]
I believe I've identified the sequencer's issue: https://github.com/ethereum/kzg-ceremony-sequencer/issues/133

**Comment by PlasmaPower** [comment]
This should be fixed now that that PR has been deployed :)

**Comment by NicoSerranoP** [comment]
Thank you very much for your help in this 🖖🏽 ! I will close this PR for now
